### ISSUE TITLE
mqtt broker hardcoded?

### ISSUE THREAD

**Issue by ggari-robotnik** [RobotnikIstobalAI2/robotnik_rmf_fleet_adapter#11]
As far as I understand the mqtt broker ip and port is hardcoded

https://github.com/RobotnikIstobalAI2/fleet-adapter/blob/9d0b98cc1a0fb6e1e56b89627cb1f0dddf39c521/fleet_adapter_mqtt/fleet_adapter_mqtt/fleet_adapter_mqtt/RobotClientAPI.py#L118

Add on the config.yaml the following data under `fleet_manager`

https://github.com/RobotnikIstobalAI2/fleet-adapter/blob/9d0b98cc1a0fb6e1e56b89627cb1f0dddf39c521/fleet_adapter_mqtt/fleet_adapter_mqtt/config.yaml#L6

1. Remove `prefix` if do not cause problems
2. Add `broker` where the mqtt broker ip or site is added
3. Add `port` where the mqtt port is configured
4. Add `keepalive` where the conection keepalive in seconds is set
5. Add `anonymous_access` boolean flag

```yaml
  fleet_manager:
    broker: "127.0.0.1"
    # broker: "mqtt.robotnik.cloud"
    port: 1883
    keep_alive: 60
    anonymous_access: true
    user: "some_user"
    password: "some_password"

```

6. On `RobotAPI` constructor change the definition to  use of the yaml parameters `broker`, `port`, `keep_alive`, `anonymous_access`, `user` , `password` are used https://github.com/RobotnikIstobalAI2/fleet-adapter/blob/9d0b98cc1a0fb6e1e56b89627cb1f0dddf39c521/fleet_adapter_mqtt/fleet_adapter_mqtt/fleet_adapter_mqtt/RobotClientAPI.py#L80
7. modify the `connect_mqtt` method to add all new parametes https://github.com/RobotnikIstobalAI2/fleet-adapter/blob/9d0b98cc1a0fb6e1e56b89627cb1f0dddf39c521/fleet_adapter_mqtt/fleet_adapter_mqtt/fleet_adapter_mqtt/RobotClientAPI.py#L109
9. If the `anonymous_access`  is set to `false` do not pass user and password to client using 
```python
client.username_pw_set(username, password)
```
10. Modfiy acordingly https://github.com/RobotnikIstobalAI2/fleet-adapter/blob/9d0b98cc1a0fb6e1e56b89627cb1f0dddf39c521/fleet_adapter_mqtt/fleet_adapter_mqtt/fleet_adapter_mqtt/fleet_adapter.py#L166
10. It's possible to add more in the future

**Comment by EmimaJiva** [comment]
@ggari-robotnik Could you test it, please?
