### ISSUE TITLE
Error to launch 

### ISSUE THREAD

**Issue by EmimaJiva** [RobotnikIstobalAI2/robotnik_rmf_fleet_adapter#15]
@ggari-robotnik I get this error when I launch the fleet adapter, following the Readme steps. 
![MicrosoftTeams-image (4)](https://github.com/RobotnikIstobalAI2/fleet-adapter/assets/121794419/814d4a75-b280-4e01-ab1e-59b9e7a82718)

**Comment by sandra-Robotnik** [comment]
@EmimaJiva 

To solve this issue, enter into the branch `humble-devel` of the [fleet-adapter](https://github.com/RobotnikIstobalAI2/fleet-adapter/tree/humble-devel) repository. Then enter into the [docker](https://github.com/RobotnikIstobalAI2/fleet-adapter/tree/humble-devel/docker) folder.

In the [Dockerfile](https://github.com/RobotnikIstobalAI2/fleet-adapter/blob/humble-devel/docker/Dockerfile), it is necessary to modify the variable name of the line 106 from "ROS_STARTUP_TYPE" to "STARTUP_TYPE".
![image](https://github.com/RobotnikIstobalAI2/fleet-adapter/assets/98813736/58cb50ca-0638-4234-a318-72a8cd126493)

After that, in a shell write the following instructions:
```
cd ~/fleet-adapter/docker
docker compose -f build.yaml build --no-cache
docker compose up
```

@ggari-robotnik @rafa-martin
