### ISSUE TITLE
Explain how create custom missions

### ISSUE THREAD

**Issue by sandra-Robotnik** [RobotnikIstobalAI2/robotnik_rmf_fleet_adapter#19]
Readme or other file explaining how to create a custom mission

**Comment by EmimaJiva** [comment]
@ggari-robotnik  @sandra-Robotnik I have added the file [CustomMission.md](https://github.com/RobotnikIstobalAI2/fleet-adapter/blob/humble-devel/CustomMission.md) explaining how to launch the custom mission created and what steps to follow to create another custom mission.
Can you test to launch the custom mission I have created?

**Comment by sandra-Robotnik** [comment]
Hi @EmimaJiva , I will tested tomorrow morning
