### ISSUE TITLE
Send the robot to charge when the battery is low

### ISSUE THREAD

**Issue by EmimaJiva** [RobotnikIstobalAI2/robotnik_rmf_fleet_adapter#21]

**Comment by EmimaJiva** [comment]
@ggari-robotnik @sandra-Robotnik I have added comments [Comments.md](https://github.com/RobotnikIstobalAI2/general-task-n-issues/blob/main/Comments/Comments.md) on how the system works.

**Comment by EmimaJiva** [comment]
I added comments [README.md](https://github.com/RobotnikIstobalAI2/open-rmf-deployment/blob/devel/README.md) to explain how the battery related variables work.

**Comment by ggari-robotnik** [comment]
explained here [memoria_final.md](https://github.com/RobotnikIstobalAI2/general-task-n-issues/blob/main/FinalDoc/memoria_final.md#ir-al-punto-de-carga-autom%C3%A1ticamente)

**Comment by ggari-robotnik** [comment]
related to [ Robot charging #18 ](https://github.com/RobotnikIstobalAI2/open-rmf-deployment/issues/18)
