### ISSUE TITLE
Send the robot to open a door

### ISSUE THREAD

**Issue by sandra-Robotnik** [RobotnikIstobalAI2/robotnik_rmf_fleet_adapter#22]
Incorporate the necessary code and/or configurations into the fleet-adapter to enable door opening functionality.

Additionally, develop a node (similar to the delivery node), comprising an MQTT component to receive the door commands via MQTT messages, and a ROS component to receive the command and respond with a message confirming the door is open (e.g., "Ok", "True", etc.) after a specified delay (e.g., 5 seconds).

![Image](https://github.com/RobotnikIstobalAI2/fleet-adapter/assets/98813736/1833be25-7339-41d1-9d52-cbb24bb9ca08)

- **Note:** There is no need to generate a Gazebo world with a door. Instead, it is sufficient to specify that one of the points in the navigation graph possesses the property of being a door.

**Comment by EmimaJiva** [comment]
@ggari-robotnik @sandra-Robotnik Four door types are supported: "hinged", "double_hinged", "sliding" and "double_sliding" on traffic editor. Which type I should use?

**Comment by ggari-robotnik** [comment]
@EmimaJiva use sliding door type at the moment
