### ISSUE TITLE
Problem with the Docker image of the fleet-adapter in humble-devel branch

### ISSUE THREAD

**Issue by sandra-Robotnik** [RobotnikIstobalAI2/robotnik_rmf_fleet_adapter#5]
When I tried to run the `fleet-adapter` docker on the `humble-devel` branch, I got the same error as with the `rmf-core` docker image reported in the "[Problem with the Docker image in humble-devel branch #10](https://github.com/RobotnikIstobalAI2/rmf-core/issues/10)" issue.
![fleet-adapter_error_2023-04-25_09-09](https://user-images.githubusercontent.com/98813736/234202257-28f85262-b02d-44d1-a189-2a829f6c9f85.png)

If I replace the "rmf-core-humble-base:latest" with the "[emimajiva/rmf-core-humble-base:v2](https://hub.docker.com/r/emimajiva/rmf-core-humble-base/tags)" in the first line of the Dockerfile, the `docker compose up` of the fleet-adapter works properly as the rmf-core "[Problem with the Docker image in humble-devel branch #10](https://github.com/RobotnikIstobalAI2/rmf-core/issues/10)" issue.

**Comment by EmimaJiva** [comment]
The same as rmf-core. You need "rmf-core-humble-base:latest" image.
![Captura de pantalla de 2023-04-25 09-42-33](https://user-images.githubusercontent.com/121794419/234208539-c30acce8-268c-4814-a7bd-cdbfe2abd9ed.png)

**Comment by sandra-Robotnik** [comment]
Sorry I did not see the readme of the humble-devel branch.
Thank you @EmimaJiva!
@ggari-robotnik @rafa-martin

**Comment by sandra-Robotnik** [comment]
I still have a problem with the `humble-devel` branch of the `fleet-adapter` on my computer.

I have installed everything following the [README](https://github.com/RobotnikIstobalAI2/general-task-n-issues/blob/main/README.md) of `general-task-n-issues` repository on two different NUCs and in my laptop. The first NUC has Ubuntu 22.04 OS and native ROS 2 Humble installed. The second NUC has Ubuntu 20.04 OS, ROS 1 Noetic and ROS 2 Foxy. And my laptop has Ubuntu 22.04 OS and native ROS 2 Humble installed.

On both NUC I have deleted in all directories used for open-rmf simulation the nvidia references in the `docker-compose.yaml` files. In other words, I have deleted these lines from every `docker-compose.yaml` used:

```
  runtime: nvidia
  deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
After that, everything in the NUCs open-rmf simulation works fine, including the humble-devel branch of the fleet-adapter.

However, in my laptop I tried to run the simulation doing two different tests. The first one was with the original files and following the [README](https://github.com/RobotnikIstobalAI2/general-task-n-issues/blob/main/README.md) of `general-task-n-issues` repository steps. In the second one, I did the same as with the NUCs, deleting the nvidia references in the `docker-compose.yaml` files. And in both tests I have the same error in the fleet-adapter.
![fleet_adapter_error_2023-04-26_08-15](https://user-images.githubusercontent.com/98813736/234537521-3eb73c2a-d0bf-43d6-822a-6e032a457efb.png)

I did the following:

- Shell_1:
```
cd rbkairos_sim
git checkout noetic-devel
export ROS_BU_PKG="rbkairos_sim_bringup"
export ROS_BU_LAUNCH="rbkairos_complete.launch"
cd docker
docker compose build
docker compose up
```
- Shell_2:
```
cd mqtt-broker
git checkout all-changes
docker compose up -d
```
- Shell_3:
```
cd mqtt-bridge
git checkout melodic-devel
cd docker
docker compose build
docker compose up
```
- Shell_4:
```
cd rmf-core-base-docker
git checkout humble-devel
cd docker
docker compose build --pull --no-cache
docker compose up
```
- Shell_5:
```
cd rmf-core
git checkout humble-devel
cd docker
docker compose build
docker compose up
```
To this point, everything was fine.
![washcarrob_shells_2023-04-26_08-08](https://user-images.githubusercontent.com/98813736/234540065-3d853fe9-eb48-46d1-8c50-4a5df7de9713.png)

![wascarrob_sim_2023-04-26_08-10](https://user-images.githubusercontent.com/98813736/234540099-fa4ac3d1-219a-4192-8ba4-d096905bde3f.png)

But installing the fleet adapter like this:
- Shell_6:
```
git clone https://github.com/RobotnikIstobalAI2/fleet-adapter.git
cd fleet-adapter
git checkout humble-devel
cd docker
docker compose build
```
![fleet_adapter_installation_2023-04-26_08-15](https://user-images.githubusercontent.com/98813736/234541015-6880f82e-acb1-4d90-a696-2a87253ca1cb.png)

I got this error after doing `docker compose up`.
![fleet_adapter_error_2023-04-26_08-15](https://user-images.githubusercontent.com/98813736/234541446-053a1ef6-2fdc-4d8f-9fb4-7e967761e754.png)

@EmimaJiva @ggari-robotnik  @rafa-martin @maffan-96, did it happened to you?
Do you know how to solve it?

**Comment by sandra-Robotnik** [comment]
To fix the error do the following:

- Go to the humble-devel branch of the fleet-adapter.
```
git clone https://github.com/RobotnikIstobalAI2/fleet-adapter.git
cd fleet-adapter
git checkout humble-devel
```

- Go to the location of the file that is failing and edit it:
```
cd fleet_adapter_template/fleet_adapter_template/fleet_adapter_template/
nano fleet_adapter.py
```
- Delete the space in line 308 and save the changes.

- Execute again the fleet-adapter container:
```
cd ../../..
cd docker
docker compose build
docker compose up
```
Thank you @EmimaJiva
@ggari-robotnik @rafa-martin @maffan-96
