### ISSUE TITLE
GPU selection in docker compose

### ISSUE THREAD

**Issue by sandra-Robotnik** [RobotnikIstobalAI2/robotnik_rmf_fleet_adapter#7]
Add the possibility to select if you want to use the GPU or not.

To do it, follow the example of the [rb_theron_sim](https://github.com/RobotnikAutomation/rb_theron_sim) repository in the `melodic-devel` branch.
- In the `docker` directory:
   -   Add two docker compose files for the different GPUs, use the examples of the [docker-compose-nvidia.yaml](https://github.com/RobotnikAutomation/rb_theron_sim/blob/melodic-devel/docker/docker-compose-nvidia.yaml) and [docker-compose-intel.yaml](https://github.com/RobotnikAutomation/rb_theron_sim/blob/melodic-devel/docker/docker-compose-intel.yaml).
  -  Choose on of them for the docker-compose.yaml file as it is done in the [docker-compose.yaml](https://github.com/RobotnikAutomation/rb_theron_sim/blob/melodic-devel/docker/docker-compose.yaml) of the `rb_theron_sim` repository.
- In the README.md:
  - Add these commands in the instructions to run the docker (these commands have been extracted from the `Usage` section of `rb_theron_sim` [README.md](https://github.com/RobotnikAutomation/rb_theron_sim/blob/melodic-devel/README.md) ):
```
nvidia-smi &>/dev/null \
&& ln -sf docker-compose-nvidia.yml docker-compose.yml \
|| ln -sf docker-compose-intel.yml docker-compose.yml
```

**Comment by ggari-robotnik** [comment]
not required
