### ISSUE TITLE
fleet adapter robot speed

### ISSUE THREAD

**Issue by ggari-robotnik** [RobotnikIstobalAI2/robotnik_rmf_fleet_adapter#9]
RMF thinks that the robot can move quicker than the real one, please tweak de config file in order to get closer to the sim movements.

**Comment by EmimaJiva** [comment]
The yellow circles move from point to point in the navigation and don't "follow the robot". The speed has been changed in the configuration file, according to the navigation file **teb_local_planner_omni_params.yaml**.
